### ISSUE TITLE
NetBSD package nearly ready

### ISSUE THREAD

**Issue by 0323pin** [nik012003/ripdrag#12]
Hi,

I've just packaged `ripdrag` for NetBSD/pkgsrc.
The package is currently in the wip (work-in-progess) repo, since we have a branch freeze coming-up in a couple of days.

I will import the package into the main package repo once the freeze is over. Also, I want to look into why it's printing warnings about libEGL. The package is working as it should, though.

Here's the merge log, in case you're interested https://mail-index.netbsd.org/pkgsrc-wip-changes/2022/09/16/msg024969.html

**Comment by nik012003** [comment]
That's awesome! Thank you so much. 
Unfortunately I'm not very familiar with NetBSD, so I don't know how to fix the warning. Perhaps we could look if there are other gtk4-rs projects that do that and copy the fix.

**Comment by 0323pin** [comment]
@nik012003 oh no, don't worry. I think linking it at compile time should be enough.
But, as mentioned, we will enter a commit freeze rather soon, so I was not in a hurry to fix that. Will look into it before moving it to the main repo.

Will keep you posted.

**Comment by 0323pin** [comment]
See, https://github.com/nik012003/ripdrag/pull/13
