### ISSUE TITLE
Can't install ripdrag on Kubuntu because rustc is too old

### ISSUE THREAD

**Issue by FunctionDJ** [nik012003/ripdrag#29]
Full error upon running `cargo install ripgrep` (non-sudo):
```
error: failed to compile `ripdrag v0.4.2`, intermediate artifacts can be found at `/tmp/cargo-installItzQP5`

Caused by:
  package `glib-macros v0.18.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.67.1
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
```

**Comment by nik012003** [comment]
Uninstall cargo from apt:
`sudo apt remove cargo`
and try installing cargo with rustup:
`curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh`
This should install the latest rust toolchain and allow you to build ripdrag. Let me know if this fixes it, so I can update the instructions for ubuntu. Thanks

**Comment by FunctionDJ** [comment]
@nik012003 installation worked and i can run ripdrag, but i get the following output, not sure if those warnings are significant:```
$ ripdrag 

(ripdrag:31522): Gtk-WARNING **: 15:37:01.447: Unknown key gtk-modules in /home/function/.config/gtk-4.0/settings.ini

(ripdrag:31522): Gtk-WARNING **: 15:37:01.762: GtkGizmo 0x5573b24f1cb0 (slider) reported min width -2, but sizes must be >= 0

(ripdrag:31522): Gtk-WARNING **: 15:37:01.762: GtkGizmo 0x5573b24e1c00 (slider) reported min height -2, but sizes must be >= 0
^C
```

When you update the instructions, could you please also add how to undo the installation? Thanks a lot :)

**Comment by nik012003** [comment]
The gtk-warnings shouldn't matter, unfortunately there are still a few things to iron out with new gtk versions.

The new instruction will be the ones I posted in the previous comment, so there's nothing to undo here. 
If you still wanna remove everything, you can:
uninstall ripdrag: `cargo uninstall ripdrag`
remove the toolchain: `rustup self uninstall`

**Comment by FunctionDJ** [comment]
Thanks a lot!
