### ISSUE TITLE
Error when using '-A' flag, installed using Cargo on Ubuntu 22.04

### ISSUE THREAD

**Issue by gnarlsnishi** [nik012003/ripdrag#30]
When using the `-A` or `--all-compact` flag, ripdrag fails and I get the following error message.

> thread 'main' panicked at 'Source property n-items on type GListStore not found', /home/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/object.rs:3789:21
> note: run with \`RUST_BACKTRACE=1\` environment variable to display a backtrace

Running the command again with "RUST_BACKTRACE=1" or "RUST_BACKTRACE=full" doesn't seem to give any useful information, but I can provide it if it would help.

I am using Gnome on Ubuntu 22.04, and I installed ripdrag using the recommended method from the github page.

**Comment by nik012003** [comment]
Thank you for reporting. It should be fixed in v0.4.3.
