### ISSUE TITLE
suggestion: add option to disable opening images from ripdrag

### ISSUE THREAD

**Issue by Gitleptune** [nik012003/ripdrag#32]
Current behaviour is when you click an entry in the ripdrag window it will open the image, I think there should be an option to disable it (-n/--no-click for example) as:
1. I don't think the function of this utility should be an image opener, you have file managers for that (lf, ranger etc) or image viewers such as nsxiv.
2. If you are selecting selecting multiple items by CTRL clicking or SHIFT clicking it will open an image each time and that is just super annoying.

**Comment by nik012003** [comment]
Thanks for reporting this, fixed the SHIFT click bug, and added --no-click in v0.4.4
