### ISSUE TITLE
Problem with popup window on DWM

### ISSUE THREAD

**Issue by Trophe-us** [nik012003/ripdrag#35]
Moved from dragon to ripdrag when I open ripdrag file.txt a full window opens not a popup window like it does in dragon?

**Comment by tkna91** [comment]
I am using sway and the ripdrag window is showing as a floating window.
Is this the kind of work you need to do?
https://wiki.archlinux.org/title/Dwm#Floating_layout_for_some_windows

**Comment by nik012003** [comment]
Unfortunately there's no real way to mark a window as floating in both x11 and wayland :/ 
Some window managers will show non resizable windows as floating by default (this is why the main window is not resizable by default). If that's not the case, you should set window rules in your wm as tkna91 suggested.
