### ISSUE TITLE
1 file gets lost (?) when dragging & dropping to Telegram client.

### ISSUE THREAD

**Issue by FlyingButteryTuna** [nik012003/ripdrag#45]
I don't know if it's always been there or if it happens with other apps as well, but when I drag & drop files to Telegram (on wayland, haven't tested on xorg) one file is lost in the process, e.g. if there are 101 files in ripdrag, only 100 will get dropped to Telegram. And when I drop 1 file from ripdrag, Telegram doesn't register the drag&drop event at all. Other clients that I've tested seem to work just fine.
dragon also works as one would expect with Telegram, thought.

**Comment by nik012003** [comment]
Thank you for the report!
Unfortunately I wasn't able to reproduce it, but I  think the new version I just published on crates should fix your issue. Can you test it out?
If that doesn't fix your issue, can you share more information about your sysstem so I can diagnose this issue on my machine? (distro, desktop environment/window manager)
