### ISSUE TITLE
option to disable thumbnails

### ISSUE THREAD

**Issue by arctic-penguin** [nik012003/ripdrag#5]
Nice piece of software, thanks a lot!

When running `ripdrag *.jpg` in a folder that contains plenty of jpegs, it seems to render the thumbnails synchronously, which slows down the startup of the program dramatically. Would it be possible to add an option to disable thumbnails alltogether?

**Comment by nik012003** [comment]
Sure, I added --disable-thumbails option in v0.1.4 .
It just disables the loading of thumbnails from image files, but icons are still present.

Should we also add an option to disable icons completely?

**Comment by arctic-penguin** [comment]
Thank you!

I don't mind the icons at all.
