### ISSUE TITLE
using `-r` still has a minimum height as specified by `-h`

### ISSUE THREAD

**Issue by arctic-penguin** [nik012003/ripdrag#6]
If I specify the `-r` option, I can resize the window vertically and horizontally. There seems to be no minimum width, but there is a minimum height, under which I cannot get. I assume that is the standard height from `-h`?

This is on i3-gaps.

**Comment by nik012003** [comment]
Hi, thank you for reporting this issue.
It's now solved in v0.1.3
Just to clarify, now:
-h sets the *default* window height (so you can now resize it however you want)
-w sets the *minimum* window width (it limits your resize-ability)
