### ISSUE TITLE
WM_CLASS(STRING): Empty name and instance values

### ISSUE THREAD

**Issue by fqqf** [nik012003/ripdrag#9]
Usually, there is WM_CLASS property with name and instance, so i3 users could match the window.

I still can match ripdrag with title property:
```
for_window [title="ripdrag"] floating enable
```
However, these properties are there for a reason, and must be given a reasonable values
![image](https://user-images.githubusercontent.com/77983090/189911203-170d487b-f41d-4050-883c-b46b7d6e7ac2.png)

Thank you, really liked ripdrag

**Comment by nik012003** [comment]
Thank you for reporting this. Now fixed in v0.1.5
